version: 2
updates:
  - package-ecosystem: nuget
    directory: "/Odex.AspNetCore.Clarc.Infrastructure"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: nuget
    directory: "/Odex.AspNetCore.Clarc.Infrastructure.Tests"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
