<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNuGetAudit>true</EnableNuGetAudit>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>
</Project>
